# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-05 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[(b'open', b'Open'), (b'in_progress', b'In progress'), (b'completed', b'Completed'), (b'closed', b'Closed')], default='', max_length=255)),
                ('is_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoardAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardCategoryResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('board_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardCategoryStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardCellAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
                ('board_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('name', models.CharField(default='', max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[(b'active', b'Active'), (b'success', b'Success'), (b'failed', b'Failed'), (b'rejected', b'Rejected')], default='', max_length=255)),
                ('note', models.TextField(default='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
                ('board_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.BoardCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGoalObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('result', models.CharField(choices=[(b'pending', b'Pending'), (b'pass', b'Pass'), (b'failed', b'Failed')], default='', max_length=255)),
                ('note', models.TextField(default='')),
                ('board_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardGoal')),
            ],
        ),
        migrations.CreateModel(
            name='BoardNextStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_stage_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoardResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('text_color', models.CharField(default='#000000', max_length=255)),
                ('bg_color', models.CharField(default='transparent', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('result_code', models.CharField(default='default', max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStageInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(default='')),
                ('board_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStageResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('board_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(default='.', max_length=1)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('assignee', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStory')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('icon', models.CharField(default='', max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('text_color', models.CharField(default='#000000', max_length=255)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QueueRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(0, b'Low'), (10, b'Normal'), (20, b'High'), (30, b'Ultra High')], default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'planned', b'Planned'), (b'processing', b'Processing'), (b'completed', b'Completed'), (b'rejected', b'Rejected')], default='', max_length=255)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Board')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Queue')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonthlyPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('L', models.CharField(default='M', max_length=1)),
                ('B', models.CharField(default='.', max_length=1)),
                ('R', models.CharField(default='.', max_length=1)),
                ('S', models.CharField(default='.', max_length=1)),
                ('notes', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.AddField(
            model_name='queuerequest',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boarduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstorytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardTag'),
        ),
        migrations.AddField(
            model_name='boardstorytag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstoryrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstorylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstorycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstory',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstory',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Board'),
        ),
        migrations.AddField(
            model_name='boardstory',
            name='board_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardCategory'),
        ),
        migrations.AddField(
            model_name='boardstory',
            name='board_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage'),
        ),
        migrations.AddField(
            model_name='boardstory',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstageresponsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardstage',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardresponsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardnextstage',
            name='board_stage_next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage'),
        ),
        migrations.AddField(
            model_name='boardgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardcellassignment',
            name='board_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage'),
        ),
        migrations.AddField(
            model_name='boardcellassignment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardcategorystage',
            name='board_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.BoardStage'),
        ),
        migrations.AddField(
            model_name='boardcategorystage',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardcategoryresponsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='boardassignment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
    ]
