# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='new_description',
            field=models.TextField(default=''),
        ),
    ]
