FROM registry.novogenialab.com/notasquare-zero/images/nas-urad-admin:0.1

RUN pip install PyJWT

ENV APP_ENV test
ADD src/www /opt/www

# Temporarily hack linkstatic
ADD src/www/notasquare/urad_web_material/static/material /opt/web/static/material
